import React, { useEffect, useState } from 'react'; import { createRoot } from 'react-dom/client'; import BrandMark from './components/BrandMark.jsx'; import { connectWallet, readLatest, verifyClaim, contractAddress } from './genlayerClient.js'; import './styles.css'; import './veritas.css'; import './brand.css';
const emptyProof = { verdict: 'UNCERTAIN', confidence: 0, reasoning: 'Connect a deployed VeritasVerifier contract to begin.', sources: [], evidence: [] };
function App() {
 const [claim,setClaim]=useState('Urban trees reduce summer heat in cities.'); const [urls,setUrls]=useState(['https://en.wikipedia.org/wiki/Urban_heat_island']); const [wallet,setWallet]=useState(null); const [proof,setProof]=useState(null); const [tx,setTx]=useState(''); const [status,setStatus]=useState('Ready to verify through GenLayer consensus.'); const [busy,setBusy]=useState(false); const [error,setError]=useState('');
 const updateUrl=(i,v)=>setUrls(urls.map((url,index)=>index===i?v:url));
 useEffect(()=>{const pending=localStorage.getItem('veritas.pendingTx');if(pending){setTx(pending);setStatus('A previously submitted verification is still pending or needs to be checked.')}const submitted=e=>setTx(e.detail);window.addEventListener('veritas:submitted',submitted);return()=>window.removeEventListener('veritas:submitted',submitted)},[]);
 async function connect(){try{setError('');const w=await connectWallet();setWallet(w);setStatus(`Connected ${w.address.slice(0,6)}…${w.address.slice(-4)} on Studionet.`)}catch(e){setError(e.message)}}
 async function refresh(){try{setBusy(true);setError('');setProof(await readLatest());setStatus('Loaded the latest finalized on-chain verification.')}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function submit(e){e.preventDefault();try{setBusy(true);setError('');const active=wallet||await connectWallet();setWallet(active);setStatus('MetaMask will request approval. GenLayer validators will independently gather evidence and reach consensus…');const result=await verifyClaim(active.client,claim,urls.filter(Boolean));setTx(result.hash);setProof(result.proof);setStatus('Finalized on Studionet — this proof is live contract state.')}catch(e){setError(e.message)}finally{setBusy(false)}}
 const result=proof||emptyProof; return <main><nav><a className="brand" href="#top"><BrandMark/><span>veritas</span><small>GENLAYER NATIVE</small></a><button className="wallet" onClick={connect}>{wallet ? 'Wallet connected' : 'Connect MetaMask'}</button></nav><section className="hero" id="top"><p className="eyebrow">DECENTRALIZED CLAIM VERIFICATION</p><h1>Evidence reaches<br/><em>consensus.</em></h1><p className="lede">Veritas asks independent GenLayer validators to read your public sources and reason over a claim. The verdict, evidence, and confidence become live on-chain state.</p><div className="chain"><span>NETWORK</span><b>Studionet · Chain 61999</b><span>CONTRACT</span><code>{contractAddress || 'Not configured'}</code></div></section><section className="work"><form onSubmit={submit}><label htmlFor="claim">Claim to verify</label><textarea id="claim" value={claim} onChange={e=>setClaim(e.target.value)} maxLength="800" required/><label>Public evidence URLs <small>(one to three)</small></label>{urls.map((url,i)=><input key={i} className="source-input" type="url" placeholder="https://source.example/article" value={url} onChange={e=>updateUrl(i,e.target.value)} required={i===0}/>)}<div className="actions"><button type="button" className="secondary" disabled={urls.length>=3} onClick={()=>setUrls([...urls,''])}>+ Add source</button><button disabled={busy}>{busy?'Verifying on GenLayer…':'Verify on-chain →'}</button></div><p className="hint">No proxy backend: source retrieval and AI judgment run inside the Intelligent Contract.</p></form><aside className="proof"><div className="result-head"><p className="eyebrow">ON-CHAIN PROOF</p><button className="text-button" onClick={refresh} disabled={busy}>Refresh state</button></div><div className={'verdict '+result.verdict.replaceAll(' ','-').toLowerCase()}>{result.verdict}</div><div className="confidence"><span>CONFIDENCE</span><b>{result.confidence}%</b><i><em style={{width:`${result.confidence}%`}}/></i></div><p className="reasoning">{result.reasoning}</p>{result.evidence?.length>0&&<><h3>Evidence observed</h3><ul>{result.evidence.map((item,i)=><li key={i}>{item}</li>)}</ul></>}{result.sources?.length>0&&<><h3>Sources used</h3><ul>{result.sources.map(url=><li key={url}><a href={url} target="_blank" rel="noreferrer">{url}</a></li>)}</ul></>}{tx&&<p className="tx">Transaction: <code>{tx}</code></p>}</aside></section>{error&&<p className="error" role="alert">{error}</p>}<p className="status-line">{status}</p><footer><BrandMark/><span>Verification is evidence-based consensus, not a universal guarantee of truth.</span></footer></main>}
createRoot(document.getElementById('root')).render(<App/>);
